# Generated by Django 4.1.5 on 2023-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadAccounr_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Month_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_Title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Taluk_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taluk_Title', models.CharField(max_length=200)),
            ],
        ),
    ]
