# Generated by Django 4.1.5 on 2023-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabels', '0004_delete_year_field_tabel_data_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel_data',
            name='Taluk',
            field=models.CharField(max_length=200),
        ),
    ]
