# Generated by Django 4.1.5 on 2023-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabels', '0005_alter_tabel_data_taluk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabel_data',
            name='Account',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tabel_data',
            name='Month',
            field=models.CharField(max_length=200),
        ),
    ]
