# Generated by Django 4.1.5 on 2023-01-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tabels', '0006_alter_tabel_data_account_alter_tabel_data_month'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeadAccounr_Field',
            new_name='HeadAccount_Field',
        ),
    ]
